apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-config
data:
  app.js: |
    const express = require('express');
    const app = express();
    const port = 3000;

    app.get('/', (req, res) => {
      res.send('Hello World from Minikube and ArgoCD!');
    });

    app.listen(port, () => {
      console.log(`App listening at http://localhost:${port}`);
    }
  package.json: |
    {
      "name": "hello-world",
      "version": "1.0.0",
      "description": "A simple Hello World app",
      "main": "app.js",
      "scripts": {
        "start": "node app.js"
      },
      "dependencies": {
        "express": "^4.17.1"
      }
    }

